name: CI - GitHub Actions

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  blog-site-build:
    runs-on: "ubuntu-20.04"
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Python packages
        run: pip install -r requirements.txt
      - name: Install JPEGoptim and optiPNG image compressors
        run: sudo apt-get install jpegoptim optipng -y
      - name: Run JPEG optim and optiPNG to compress JPEG and PNG static images
        run: jpegoptim docs/static/img/*.jpg && optipng docs/static/img/*.png
      - name: Run Static Site Generator
        run: python site_generator.py
      - name: List generated content and repo copy
        run: ls -laR
      - name: Commit generated HTML files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Static Site Generator-created Static HTML Site
          branch: main
